### ISSUE TITLE
Running r10k deploy environment with Config File on masterless Windows node corrupts referenced gitrepo in cachedir

### ISSUE THREAD

**Issue by msaal** [puppetlabs/r10k#1071]
## Describe the Bug
Running `r10k deploy environment` for the first time on a masterless Windows node is successfully cloning the control-repo, and adding the following alternates file in `\environments\{branch}\.git\objects\info`:

```
C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects
```

As soon as `r10k deploy environment` is run for the second time on the same node, the alternates file is getting updated by shellgit provider as follows (adding 2nd line):

```
C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects
C:\ProgramData\PuppetLabs\puppet\cache\r10k/git@github.com-xxxxx-puppet-control-repo.git/objects
```

This results in the following errors in the consequent git commands and with a corrupted local git repo:
```
[2020-05-30 10:29:15 - DEBUG2] Starting process: ["git", "--git-dir", "C:/ProgramData/PuppetLabs/code/environments/production/.git", "--work-tree", "C:/ProgramData/PuppetLabs/code/environments/production", "diff-index", "--exit-code", "--name-only", "HEAD"]
[2020-05-30 10:29:15 - DEBUG2] Finished process:
Command: git --git-dir C:/ProgramData/PuppetLabs/code/environments/production/.git --work-tree C:/ProgramData/PuppetLabs/code/environments/production diff-index --exit-code --name-only HEAD
Stderr:
error: object directory C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects? does not exist; check .git/objects/info/alternates
error: object directory C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects? does not exist; check .git/objects/info/alternates
fatal: bad object HEAD
Exit code: 128
[2020-05-30 10:29:15 - WARN] Overwriting local modifications to C:/ProgramData/PuppetLabs/code/environments/production
[2020-05-30 10:29:15 - DEBUG] Updating C:/ProgramData/PuppetLabs/code/environments/production to production
[2020-05-30 10:29:15 - DEBUG2] Starting process: ["git", "--git-dir", "C:/ProgramData/PuppetLabs/code/environments/production/.git", "--work-tree", "C:/ProgramData/PuppetLabs/code/environments/production", "checkout", "374d55cec5b694c8711d5b41357269b57ed5329e", "--force"]
[2020-05-30 10:29:15 - DEBUG2] Finished process:
Command: git --git-dir C:/ProgramData/PuppetLabs/code/environments/production/.git --work-tree C:/ProgramData/PuppetLabs/code/environments/production checkout 374d55cec5b694c8711d5b41357269b57ed5329e --force
Stderr:
error: object directory C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects? does not exist; check .git/objects/info/alternates
error: object directory C:/ProgramData/PuppetLabs/puppet/cache/r10k/git@github.com-xxxxx-puppet-control-repo.git/objects? does not exist; check .git/objects/info/alternates
fatal: reference is not a tree: 374d55cec5b694c8711d5b41357269b57ed5329e
Exit code: 128
```

It looks like that when syncing the alternates file, there are some issues with forward- and backslashes. For testing purposes, I commented the `synch_alternates` function out in `thin_repository.rb`; thus, the alternates file was not getting updated by r10k, and everything went smoothly without any errors.

## Expected Behavior
Running `r10k deploy environment` should not cause any issues after successfully cloning the control-repo.

## Steps to Reproduce
1. Run `r10k deploy environment` on a Windows-node in masterless environment. The control-repo is getting cloned, git object database is available in cachedir.
2. Run `r10k deploy environment` on a Windows-node for a second time. The alternates file is getting updated with an additional line containing inconsistent slashes in the path, leading to a corrupted local git repo.

## Environment
 - r10k version 3.5.0
 - git version 2.26.2.windows.1
 - shellgit provider
 - Windows 10 Version 1909

**Comment by michaelw** [comment]
can confirm, still a problem

**Comment by michaelw** [comment]
Turns out the reason for me was two-fold:
* windows line endings (avoided by writing the r10k.conf file with unix line endings)
* set `cachedir` to use uppercase drive letter and forward slashes as path separator

This is quite brittle, and path comparison in r10k/git/alternates.rb should probably handle these cases automatically.

**Comment by michaelw** [comment]
issue is still persisting

**Comment by igalic** [comment]
looks like this issue still persists:

```
PS C:\ProgramData\PuppetLabs\code\environments> & 'C:\Program Files\Puppet Labs\Puppet\puppet\bin\r10k.bat' --config C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml deploy environment --verbose --puppetfile
INFO     -> Deploying environment C:/ProgramData/PuppetLabs/code/environments/production
WARN     -> Overwriting local modifications to C:/ProgramData/PuppetLabs/code/environments/production
ERROR    -> Command exited with non-zero exit code:
Command: git --git-dir C:/ProgramData/PuppetLabs/code/environments/production/.git --work-tree C:/ProgramData/PuppetLabs/code/environments/production checkout 3fbc3b3d63414588ca8a4aba633af5ab108ffcde --force
Stderr:
error: object directory C:/Users/mina_galic/AppData/Local/r10k/git/git@codeberg.org-pp-homework-windows.git/objects? does not exist; check .git/objects/info/alternates
error: object directory C:/Users/mina_galic/AppData/Local/r10k/git/git@codeberg.org-pp-homework-windows.git/objects? does not exist; check .git/objects/info/alternates
fatal: reference is not a tree: 3fbc3b3d63414588ca8a4aba633af5ab108ffcde
Exit code: 128
PS C:\ProgramData\PuppetLabs\code\environments>
```

<details><summary>same as above abut with <code>--trace</code></summary>

```
PS C:\ProgramData\PuppetLabs\code\environments> & 'C:\Program Files\Puppet Labs\Puppet\puppet\bin\r10k.bat' --config C:\ProgramData\PuppetLabs\r10k\etc\r10k.yaml deploy environment --verbose --puppetfile --trace
INFO     -> Deploying environment C:/ProgramData/PuppetLabs/code/environments/production
WARN     -> Overwriting local modifications to C:/ProgramData/PuppetLabs/code/environments/production
ERROR    -> Command exited with non-zero exit code:
Command: git --git-dir C:/ProgramData/PuppetLabs/code/environments/production/.git --work-tree C:/ProgramData/PuppetLabs/code/environments/production checkout 3fbc3b3d63414588ca8a4aba633af5ab108ffcde --force
Stderr:
error: object directory C:/Users/mina_galic/AppData/Local/r10k/git/git@codeberg.org-pp-homework-windows.git/objects? does not exist; check .git/objects/info/alternates
error: object directory C:/Users/mina_galic/AppData/Local/r10k/git/git@codeberg.org-pp-homework-windows.git/objects? does not exist; check .git/objects/info/alternates
fatal: reference is not a tree: 3fbc3b3d63414588ca8a4aba633af5ab108ffcde
Exit code: 128
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/util/subprocess.rb:78:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/git/shellgit/base_repository.rb:135:in `git'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/git/shellgit/thin_repository.rb:58:in `git'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/git/shellgit/working_repository.rb:59:in `checkout'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/git/stateful_repository.rb:66:in `sync'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/environment/git.rb:67:in `sync'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/deploy/environment.rb:160:in `visit_environment'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/visitor.rb:27:in `visit'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/environment/with_modules.rb:79:in `accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/source/base.rb:89:in `block (2 levels) in accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/source/base.rb:88:in `each'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/source/base.rb:88:in `block in accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/deploy/environment.rb:144:in `visit_source'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/visitor.rb:27:in `visit'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/source/base.rb:87:in `accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/deployment.rb:108:in `block (2 levels) in accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/deployment.rb:107:in `each'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/deployment.rb:107:in `block in accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/deploy/environment.rb:119:in `visit_deployment'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/visitor.rb:27:in `visit'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/deployment.rb:106:in `accept'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/deploy/environment.rb:75:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/runner.rb:33:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/lib/r10k/action/cri_runner.rb:67:in `call'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/cri-2.15.10/lib/cri/command_dsl.rb:303:in `block in runner'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/cri-2.15.10/lib/cri/command.rb:360:in `run_this'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/cri-2.15.10/lib/cri/command.rb:296:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/cri-2.15.10/lib/cri/command.rb:314:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/cri-2.15.10/lib/cri/command.rb:314:in `run'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/gems/2.7.0/gems/r10k-3.13.0/bin/r10k:7:in `<top (required)>'
C:/Program Files/Puppet Labs/Puppet/puppet/bin/r10k:23:in `load'
C:/Program Files/Puppet Labs/Puppet/puppet/bin/r10k:23:in `<main>'
PS C:\ProgramData\PuppetLabs\code\environments>
```

</details>

**Comment by Magisus** [comment]
The `community interest` label should prevent this being marked as stale again. Sorry about the spam. Hopefully we can get to this at some point, but we're also definitely happy to review and accept PRs if one of you Windows users wants to give that a shot 🙂

**Comment by mwaggett** [comment]
Hi @msaal, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.
