### ISSUE TITLE
TypeError - "no implicit conversion of nil into String" - when running test-kitchen converge

### ISSUE THREAD

**Issue by jchoksijudopay** [puppetlabs/r10k#1188]
## Describe the Bug
With the v3.10.0 version of r10k module, we get a TypeError when running test-kitchen converge <imagename> and this works fine with prior version of r10k. e.g. The last version which works correctly is v3.9.3.

## Expected Behavior
We were not expecting upgrade to v3.10.0 to result in a TypeError.

## Steps to Reproduce
I don't think the issue is specific to our puppet manifests and so it should be reproducible by running:

- kitchen create imagename
- kitchen converge imagename

## Environment
 - Version: v3.10.0
 - Platform: Centos 7

## Additional Context
Log msgs:

```
I, [2021-07-20T17:17:25.409449 #59]  INFO -- splunkserver-centos7: -----> Converging <splunkserver-centos7>...
I, [2021-07-20T17:17:25.409947 #59]  INFO -- splunkserver-centos7: Preparing files for transfer
I, [2021-07-20T17:17:25.410009 #59]  INFO -- splunkserver-centos7: Preparing modules
I, [2021-07-20T17:17:25.410190 #59]  INFO -- splunkserver-centos7: Resolving module dependencies with R10K-Puppet 3.10.0...
E, [2021-07-20T17:17:25.411373 #59] ERROR -- splunkserver-centos7: Converge failed on instance <splunkserver-centos7>.
E, [2021-07-20T17:17:25.411420 #59] ERROR -- splunkserver-centos7: ------Exception-------
E, [2021-07-20T17:17:25.411427 #59] ERROR -- splunkserver-centos7: Class: TypeError
E, [2021-07-20T17:17:25.411431 #59] ERROR -- splunkserver-centos7: Message: no implicit conversion of nil into String
E, [2021-07-20T17:17:25.411435 #59] ERROR -- splunkserver-centos7: ----------------------
E, [2021-07-20T17:17:25.411447 #59] ERROR -- splunkserver-centos7: ------Backtrace-------
E, [2021-07-20T17:17:25.411451 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/module_loader/puppetfile.rb:186:in `initialize'
E, [2021-07-20T17:17:25.411455 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/module_loader/puppetfile.rb:186:in `new'
E, [2021-07-20T17:17:25.411459 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/module_loader/puppetfile.rb:186:in `cleanpath'
E, [2021-07-20T17:17:25.411462 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/module_loader/puppetfile.rb:31:in `initialize'
E, [2021-07-20T17:17:25.411466 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/puppetfile.rb:82:in `new'
E, [2021-07-20T17:17:25.411469 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/r10k-3.10.0/lib/r10k/puppetfile.rb:82:in `initialize'
E, [2021-07-20T17:17:25.411473 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet/r10k.rb:50:in `new'
E, [2021-07-20T17:17:25.411477 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet/r10k.rb:50:in `resolve'
E, [2021-07-20T17:17:25.411481 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet_apply.rb:1438:in `block in resolve_with_r10k'
E, [2021-07-20T17:17:25.411484 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet_apply.rb:1436:in `synchronize'
E, [2021-07-20T17:17:25.411488 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet_apply.rb:1436:in `resolve_with_r10k'
E, [2021-07-20T17:17:25.411492 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet_apply.rb:1276:in `prepare_modules'
E, [2021-07-20T17:17:25.411496 #59] ERROR -- splunkserver-centos7: /root/.chefdk/gem/ruby/2.6.0/gems/kitchen-puppet-3.5.2/lib/kitchen/provisioner/puppet_apply.rb:564:in `create_sandbox'
E, [2021-07-20T17:17:25.411499 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/provisioner/base.rb:71:in `call'
E, [2021-07-20T17:17:25.411503 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:409:in `block in converge_action'
E, [2021-07-20T17:17:25.411507 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2021-07-20T17:17:25.411510 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
E, [2021-07-20T17:17:25.411514 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2021-07-20T17:17:25.411521 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
E, [2021-07-20T17:17:25.411525 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:404:in `converge_action'
E, [2021-07-20T17:17:25.411528 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2021-07-20T17:17:25.411532 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2021-07-20T17:17:25.411536 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2021-07-20T17:17:25.411539 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
E, [2021-07-20T17:17:25.411543 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
E, [2021-07-20T17:17:25.411546 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:140:in `converge'
E, [2021-07-20T17:17:25.411550 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
E, [2021-07-20T17:17:25.411554 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2021-07-20T17:17:25.411557 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2021-07-20T17:17:25.411561 #59] ERROR -- splunkserver-centos7: /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2021-07-20T17:17:25.411564 #59] ERROR -- splunkserver-centos7: ----End Backtrace-----

```

Note: Running with kitchen converge -D --log-level=debug does not result in any further information that can identify what is causing the type error.

**Comment by binford2k** [comment]
What are the contents of your `Puppetfile` and what r10k command is your workflow invoking? What is the current working directory when r10k is invoked and what's the full path of the `Puppetfile`?

**Comment by jchoksijudopay** [comment]
> What are the contents of your Puppetfile

Contents of ~/Work/src/Puppet/modules/splunk_judo/Puppetfile
```
#mod 'puppet/splunk', :latest
mod 'puppetlabs/stdlib', :latest
mod 'puppet/archive', :latest
mod 'puppetlabs/concat', :latest
mod 'puppetlabs/inifile', :latest
mod 'puppetlabs/powershell', :latest
mod 'puppetlabs/pwshlib', :latest
mod 'puppetlabs/registry', :latest
mod 'puppetlabs/lvm', :latest
mod 'svarrette/ulimit', :latest
mod 'alexharvey/disable_transparent_hugepage', :latest
mod 'puppetlabs/firewall', :latest
mod 'puppetlabs/dsc_lite', '2.0.2'
mod 'hbuckle/powershellmodule', :latest
mod 'kemra102/auditd', :latest
mod 'puppetlabs/reboot', :latest
mod 'puppetlabs/chocolatey', :latest
mod 'jpi/crypto_win', :latest
mod 'puppet/windowsfeature', :latest
mod 'ayohrling/local_security_policy', :latest
mod 'herculesteam/augeasproviders_ssh', :latest
mod 'herculesteam/augeasproviders_core', :latest
```

> What r10k command is your workflow invoking?

We use [kitchen-puppet](https://github.com/neillturner/kitchen-puppet) and I'm guessing what you want to know is this: https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet/r10k.rb#L50


> What is the current working directory when r10k is invoked and what's the full path of the Puppetfile

~/Work/src/Puppet/modules/splunk_judo/
and
~/Work/src/Puppet/modules/splunk_judo/Puppetfile

**Comment by mwaggett** [comment]
Looks like we don't know how to handle an unset `basedir`.

**Comment by mwaggett** [comment]
This is explicitly trying to initialize with a `nil` `basedir`: https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet/r10k.rb#L50

**Comment by jchoksijudopay** [comment]
> This is explicitly trying to initialize with a `nil` `basedir`: https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet/r10k.rb#L50

Should I close the issue here and raise an issue with the developers of kitchen-puppet? i.e. is it incorrect for basedir to be nil?

**Comment by mwaggett** [comment]
@jchoksijudopay I've opened an issue with kitchen-puppet: https://github.com/neillturner/kitchen-puppet/issues/214

I've also opened two tickets to improve the error message when `basedir` is nil and to improve the documentation around how these params are used: https://tickets.puppetlabs.com/browse/RK-370 & https://tickets.puppetlabs.com/browse/RK-371

Thanks for bringing this to our attention!
