### ISSUE TITLE
ArgumentError: Logger must have a name

### ISSUE THREAD

**Issue by justenwalker** [puppetlabs/r10k#17]
When running `r10k synchronize` I get this error: 

```
Runtime error: #<ArgumentError: Logger must have a name>
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/logging.rb:12:in `new'
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/logging.rb:12:in `logger'
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/module/forge.rb:44:in `sync!'
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/action/module.rb:27:in `call'
/var/lib/gems/1.8/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
/var/lib/gems/1.8/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/action/environment.rb:38:in `call'
/var/lib/gems/1.8/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
/var/lib/gems/1.8/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/cli/synchronize.rb:37:in `command'
/var/lib/gems/1.8/gems/cri-2.3.0/lib/cri/command.rb:296:in `call'
/var/lib/gems/1.8/gems/cri-2.3.0/lib/cri/command.rb:296:in `run_this'
/var/lib/gems/1.8/gems/cri-2.3.0/lib/cri/command.rb:249:in `run'
/var/lib/gems/1.8/gems/cri-2.3.0/lib/cri/command.rb:262:in `run'
/var/lib/gems/1.8/gems/r10k-0.0.10/bin/r10k:7
/usr/local/bin/r10k:19:in `load'
/usr/local/bin/r10k:19
```

It seems that `self.class.name` in Logger is not set for Forge.

As a work-around I applied a patch to `/lib/r10k/logging.rb`

``` ruby
  def logger
    unless @logger
      @logger = Log4r::Logger.new(self.class.name || 'COMMON')
      @logger.add R10K::Logging.outputter
    end
    @logger
  end
```

However the real solution may be to make sure all classes that include Logging have a name, or have some other convention for initializing the Log4r name.

**Comment by justenwalker** [comment]
Actually, nevermind. I seem to have based this change on 0.0.10 and not master. Looks like it uses self.logger_name instead. It has already been fixed with 92a2104
