### ISSUE TITLE
if a source can't be fetched,  unmanaged directories should not be removed

### ISSUE THREAD

**Issue by bunkzilla** [puppetlabs/r10k#194]
Filing this issue based on a conversation that took place in issue 193.   

I ran the deployment environment with github spelled properly   I then changed it to glithub and it removed the existing environments. 

```
 r10k deploy environment -v  debug2 --trace
Faraday: you may want to install system_timer for reliable timeouts
[R10K::Source::Git - INFO] Determining current branches for "https://glithub.com/glarizza/puppet_repository.git"
[R10K::Git::Cache - DEBUG] Creating new git cache for "https://glithub.com/glarizza/puppet_repository.git"
[R10K::Git::Cache - DEBUG1] Execute: git clone --mirror https://glithub.com/glarizza/puppet_repository.git /var/cache/r10k/https---glithub.com-glarizza-puppet_repository.git
[R10K::Git::Cache - DEBUG2] [git clone --mirror https://glithub.com/glarizza/puppet_repository.git /var/cache/r10k/https---glithub.com-glarizza-puppet_repository.git] STDOUT: Initialized empty Git repository in /var/cache/r10k/https---glithub.com-glarizza-puppet_repository.git/
[R10K::Git::Cache - DEBUG2] [git clone --mirror https://glithub.com/glarizza/puppet_repository.git /var/cache/r10k/https---glithub.com-glarizza-puppet_repository.git] STDERR: error: SSL: certificate subject name 'ssl2000.cloudflare.com' does not match target host name 'glithub.com' while accessing https://glithub.com/glarizza/puppet_repository.git/info/refs

fatal: HTTP request failed
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Deployment::DeployEnvironments:0x7fb5c5260c78> failed while running: Couldn't update git cache for https://glithub.com/glarizza/puppet_repository.git: "fatal: HTTP request failed"
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/git/cache.rb:73:in `sync!'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/git/cache.rb:52:in `sync'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/source/git.rb:67:in `preload!'
/usr/lib/ruby/gems/1.8/gems/log4r-1.1.10/lib/log4r/outputter/outputterfactory.rb:50:in `to_proc'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/deployment.rb:28:in `each'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/deployment.rb:28:in `preload!'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/task/deployment.rb:76:in `call'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/task_runner.rb:26:in `run'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/task_runner.rb:21:in `catch'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/task_runner.rb:21:in `run'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/lib/r10k/cli/deploy.rb:67:in `command'
/usr/lib/ruby/gems/1.8/gems/cri-2.5.0/lib/cri/command.rb:298:in `call'
/usr/lib/ruby/gems/1.8/gems/cri-2.5.0/lib/cri/command.rb:298:in `run_this'
/usr/lib/ruby/gems/1.8/gems/cri-2.5.0/lib/cri/command.rb:251:in `run'
/usr/lib/ruby/gems/1.8/gems/cri-2.5.0/lib/cri/command.rb:264:in `run'
/usr/lib/ruby/gems/1.8/gems/r10k-1.3.4/bin/r10k:7
/usr/bin/r10k:19:in `load'
/usr/bin/r10k:19
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments

r10k version
Faraday: you may want to install system_timer for reliable timeouts
1.3.4

```

**Comment by bastelfreak** [comment]
I run into the same issue with a misspelled git URI:

```
[root@master puppet]# r10k deploy environment -pv
[R10K::Source::Git - INFO] Determining current branches for   "ssh://git@master.puppet.local:r10k-management"
[R10K::TaskRunner - ERROR] Task #  <R10K::Task::Deployment::DeployEnvironments:0x0000000115bed0> failed while running:   Couldn't update git cache for ssh://git@master.puppet.local:r10k-management: "fatal: Could   not read from remote repository."
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from   /etc/puppet/environments
[root@master puppet]#
```

**Comment by rnelson0** [comment]
Can you add the output of ls -laR /etc/puppet/environments @bastelfreak?

**Comment by bastelfreak** [comment]
```
[root@master puppet]# ls -laR /etc/puppet/environments
/etc/puppet/environments:
insgesamt 4
drwxr-xr-x. 2 root root    6 10. Okt 16:02 .
drwxr-xr-x. 5 root root 4096 10. Okt 11:58 ..
[root@master puppet]#
```

**Comment by bastelfreak** [comment]
Just FYI, I'm using r10k 1.3.4 installed via gems.

**Comment by adrienthebo** [comment]
As is discussed in https://github.com/adrienthebo/r10k/issues/193#issuecomment-59579614 this issue duplicates GH-193, so I'm closing this issue in favor of the earlier. Sorry for causing the duplication of this ticket!
