### ISSUE TITLE
r10k deploy does not validate the structure of r10k.yaml

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#203]
If r10k.yaml has the following typo:

``` yaml

---
source:
  control:
    # ...
```

r10k will try to iterate over the nonexistent element `sources` instead of source and raise an error:

```
 bexec r10k deploy environment -v --trace
[R10K::Util::Attempt - ERROR] undefined method `map' for nil:NilClass
/home/adrien/development/r10k/lib/r10k/deployment.rb:105:in `load_sources'
/home/adrien/development/r10k/lib/r10k/deployment.rb:48:in `sources'
/home/adrien/development/r10k/lib/r10k/deployment.rb:33:in `preload!'
/home/adrien/development/r10k/lib/r10k/action/deploy/environment.rb:34:in `block in call'
[...]
```

The contents of r10k.yaml should be checked to ensure only valid keys are defined and that all required keys are available.

**Comment by adrienthebo** [comment]
Partially resolved in https://tickets.puppetlabs.com/browse/RK-4; https://tickets.puppetlabs.com/browse/RK-51 tracks the larger strict validation issue. Closing this issue in favor of RK-51.
