### ISSUE TITLE
r10k 1.5.0 failing with faraday errors

### ISSUE THREAD

**Issue by maxenced** [puppetlabs/r10k#390]
Hi,

just tried r10k 1.5.0 with both faraday 0.9.0 and 0.9.1, both are raising : 

``` ruby
/var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday.rb:99:in `method_missing': undefined method `register_middleware' for #<Faraday::Connection:0x0000000262a2f8> (NoMethodError)
        from /var/lib/gems/1.9.1/gems/faraday_middleware-multi_json-0.0.5/lib/faraday_middleware/multi_json.rb:28:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/module_repository/forge.rb:7:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/module/forge.rb:6:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/module.rb:35:in `<module:Module>'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/module.rb:3:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/puppetfile.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/environment/git.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/environment.rb:4:in `<module:Environment>'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/environment.rb:2:in `<module:R10K>'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/environment.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/source/git.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/source.rb:35:in `<module:Source>'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/source.rb:6:in `<module:R10K>'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/source.rb:5:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/deployment.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/cli/deploy.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/lib/r10k/cli.rb:50:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/r10k-1.5.0/bin/r10k:3:in `<top (required)>'
        from /usr/local/bin/r10k:23:in `load'
        from /usr/local/bin/r10k:23:in `<main>'
```

Just rollbacked to r10k 1.4.2 which works fine. Might be related to https://github.com/reset/ridley/issues/239 

My gems are : 

**\* LOCAL GEMS ***

colored (1.2)
cri (2.6.1, 2.5.0)
faraday (0.9.0, 0.8.9)
faraday_middleware (0.9.1)
faraday_middleware-multi_json (0.0.5)
hiera (1.3.2)
json_pure (1.8.1)
log4r (1.1.10)
mini_portile (0.5.3)
multi_json (1.11.0, 1.8.4)
multipart-post (1.2.0)
r10k (1.5.0, 1.4.2, 1.4.1, 1.4.0, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.0, 1.2.1)
semantic_puppet (0.1.1)
systemu (2.5.2)

Maxence

**Comment by adrienthebo** [comment]
Could you try upgrading faraday_middleware-multi_json to 0.0.6 with faraday
0.9 and r10k 1.5 0?

**Comment by maxenced** [comment]
Works fine after I upgraded faraday_middleware-multi_json to 0.0.6 :) 
Thanks !

**Comment by adrienthebo** [comment]
I'm moving this issue to https://tickets.puppetlabs.com/browse/RK-79 and closing this out as a duplicate, thanks for reporting this issue!
