### ISSUE TITLE
`require': cannot load such file -- archive/tar/minitar (LoadError)

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/r10k#443]
I updated r10k to 2.0.0, now it fails:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- archive/tar/minitar (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/shared/puppet_forge/tar/mini.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:4:in `<class:Tar>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:3:in `<module:PuppetForge>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/shared/puppet_forge/unpacker.rb:3:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/forge/module_release.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/module/forge.rb:6:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/module.rb:35:in `<module:Module>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/module.rb:3:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/puppetfile.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/environment/git.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/environment.rb:4:in `<module:Environment>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/environment.rb:2:in `<module:R10K>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/environment.rb:1:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/source/git.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/source.rb:35:in `<module:Source>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/source.rb:6:in `<module:R10K>'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/source.rb:5:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/deployment.rb:1:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/cli/deploy.rb:2:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/lib/r10k/cli.rb:50:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/r10k-2.0.0/bin/r10k:3:in `<top (required)>'
    from /usr/local/bin/r10k:23:in `load'
    from /usr/local/bin/r10k:23:in `<main>'
```

the call:

```
r10k deploy module --environment production profiles --verbose
```

I'm running on:

```
# ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
# facter -p os
{"name"=>"CentOS", "family"=>"RedHat", "release"=>{"major"=>"7", "minor"=>"1", "full"=>"7.1.1503"}}
```

**Comment by bastelfreak** [comment]
Installing the gem minitar fixes this issue. If the gem is really needed, can you please move if from dev deps to prod deps?

**Comment by adrienthebo** [comment]
Filed this as https://tickets.puppetlabs.com/browse/RK-117. I'm going to finish up this issue on the JIRA tracker and am going to close this out as a dup. Thanks for filing this!

**Comment by adrienthebo** [comment]
See also #446.
