### ISSUE TITLE
archive-tar-minitar dependency

### ISSUE THREAD

**Issue by ktreese** [puppetlabs/r10k#447]
After installing r10k v2.0.0, r10k does not run.  The following error is produced:

```
[root@puppetmaster puppet]# /opt/puppet/bin/r10k 
/opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- archive/tar/minitar (LoadError)
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/shared/puppet_forge/tar/mini.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:4:in `<class:Tar>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:3:in `<module:PuppetForge>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/shared/puppet_forge/tar.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/shared/puppet_forge/unpacker.rb:3:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/forge/module_release.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/module/forge.rb:6:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/module.rb:35:in `<module:Module>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/module.rb:3:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/puppetfile.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/environment/git.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/environment.rb:4:in `<module:Environment>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/environment.rb:2:in `<module:R10K>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/environment.rb:1:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/source/git.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/source.rb:35:in `<module:Source>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/source.rb:6:in `<module:R10K>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/source.rb:5:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/deployment.rb:1:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/cli/deploy.rb:2:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/lib/r10k/cli.rb:50:in `<top (required)>'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/r10k-2.0.0/bin/r10k:3:in `<top (required)>'
    from /opt/puppet/bin/r10k:23:in `load'
    from /opt/puppet/bin/r10k:23:in `<main>'
[root@puppetmaster puppet]# 
```

After running a '/opt/puppet/bin/gem install archive-tar-minitar', r10k works as expected.

**Comment by adrienthebo** [comment]
This issue is also being tracked at https://github.com/puppetlabs/r10k/issues/443 and https://tickets.puppetlabs.com/browse/RK-117, and https://github.com/puppetlabs/r10k/pull/446 has been submitted to fix it. We should have that PR merged shortly and a release turned around within ~30 minutes. Since we already have those issues filed I'm going to close this issue out as a duplicate. Apologies for the duplication of work and the bug and thanks for submitting this!
