### ISSUE TITLE
Rebasing causes r10k to fail to deploy an environment.

### ISSUE THREAD

**Issue by patrobinson** [puppetlabs/r10k#590]
When I rebase a branch and push to github, this sometimes causes r10k to fail to pull the latest commit. I get the following error:

```
ERROR    -> Command exited with non-zero exit code:
Command: git --git-dir /etc/puppet/environments/scout_update/.git --work-tree /etc/puppet/environments/scout_update checkout <commit sha>
Stderr:
error: Your local changes to the following files would be overwritten by checkout:
    Puppetfile
Please, commit your changes or stash them before you can switch branches.
Aborting
Exit code: 1
```

**Comment by scotje** [comment]
That error seems to indicate that the Puppetfile inside of `/etc/puppet/environments/scout_update` has been modified locally. You're not trying to use the deployed environment as a working directory for making your changes are you?

**Comment by patrobinson** [comment]
@scotje definitely not. I've confirmed that the files that are changed look like what's in a previous commit of the branch. But since the environments are not real git checkouts it's tricky to disprove that theory.

**Comment by scotje** [comment]
Hmmm, can you add a more complete list of reproduction steps? I'll try to take a look.

**Comment by patrobinson** [comment]
Hmm, my environment has got itself into a weird state. I just created a new branch to test and commited one change. That succeeded in creating the environment but spat an error:

```
ERROR    -> Command exited with non-zero exit code:
Command: git clone git@github.com:my_org/my_repo.git /etc/puppet/environments/reproduce_r10k_breakage --refere
nce /var/cache/r10k/git@github.com-my_org-my_repo.git
Stderr:
Cloning into '/etc/puppet/environments/reproduce_r10k_breakage'...
error: Untracked working tree file 'some totally unrelated file I had not modified on my branch' would be overwritten by merge.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Then when I pushed a new commit it failed to update the environment with:

```
ERROR    -> Command exited with non-zero exit code:
Command: git --git-dir /etc/puppet/environments/reproduce_r10k_breakage/.git --work-tree /etc/puppet/environments/reproduce_r10k_breakage checkout 1bab346211a3fcf690a9ddf64096c1cb9f2a037e
Stderr:
error: Your local changes to the following files would be overwritten by checkout:
        Puppetfile
Please, commit your changes or stash them before you can switch branches.
Aborting
Exit code: 1
 trace: ["/usr/local/bin/webhook:173:in `run_command'", "/usr/local/bin/webhook:212:in `deploy'", "/usr/local/bin/webhook:139:in `block in <class:Server>'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'", "/var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'", "/var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'", "/var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'", "/usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'", "/usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'", "/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'"]
```

Note this time it referred to a file I had modified on my branch (Puppetfile)

**Comment by patrobinson** [comment]
Deleting `/etc/puppet/environments` and git cache, then running `r10k deploy environment` seemed to resolve this issue.

**Comment by scotje** [comment]
Hmmm, yeah that does sound odd. Glad you were able to resolve it and let us know if it pops up again.
