### ISSUE TITLE
Strange network issues ("Connection reset by peer", "end of file reached") while installing some modules

### ISSUE THREAD

**Issue by dploeger** [puppetlabs/r10k#670]
I'm experiencing rather strange network issues connecting to the forge when installing some modules. I'm writing "some modules", because which modules are causing the error is not determined. So some modules are installed without any problems and with some modules the installation crashes with this log:

```
[2016-11-15 08:58:44 - DEBUG2] Reading configuration from "/etc/puppetlabs/r10k/r10k.yaml"
[2016-11-15 08:58:44 - DEBUG1] Testing to see if feature pe_license is available.
[2016-11-15 08:58:44 - DEBUG2] Attempting to load library 'pe_license' for feature pe_license
[2016-11-15 08:58:44 - DEBUG2] Error while loading library pe_license for feature pe_license: cannot load such file -- pe_license
[2016-11-15 08:58:44 - DEBUG1] Feature pe_license is not available.
[2016-11-15 08:58:44 - DEBUG2] pe_license feature is not available, PE only Puppet modules will not be downloadable.
[2016-11-15 08:58:44 - INFO] Updating module /etc/puppet/environments/localdev/modules/concat
[2016-11-15 08:58:45 - ERROR] Unable to connect to https://forgeapi.puppetlabs.com: Connection reset by peer
/usr/lib/ruby/1.9.1/openssl/buffering.rb:174:in `sysread_nonblock'
/usr/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
/usr/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/usr/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
/usr/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
/usr/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
/usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
/usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
/usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
/usr/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
/usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
/usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
/usr/lib/ruby/1.9.1/net/http.rb:1027:in `get'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.2/lib/puppet_forge/connection/connection_failure.rb:9:in `call'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/var/lib/gems/1.9.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.2/lib/puppet_forge/middleware/symbolify_json.rb:64:in `call'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/var/lib/gems/1.9.1/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.2/lib/puppet_forge/v3/base.rb:69:in `request'
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.2/lib/puppet_forge/lazy_accessors.rb:85:in `fetch'
/var/lib/gems/1.9.1/gems/puppet_forge-2.2.2/lib/puppet_forge/lazy_relations.rb:61:in `block in lazy'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/module/forge.rb:68:in `expected_version'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/module/forge.rb:136:in `install'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/module/forge.rb:48:in `sync'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/puppetfile/install.rb:30:in `visit_module'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/visitor.rb:24:in `visit'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/module/base.rb:82:in `accept'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/puppetfile.rb:132:in `block (2 levels) in accept'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/puppetfile.rb:131:in `each'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/puppetfile.rb:131:in `block in accept'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/puppetfile/install.rb:24:in `visit_puppetfile'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/visitor.rb:24:in `visit'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/puppetfile.rb:130:in `accept'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/puppetfile/install.rb:14:in `call'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/runner.rb:33:in `call'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/lib/r10k/action/cri_runner.rb:67:in `call'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command_dsl.rb:223:in `block in runner'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command.rb:298:in `call'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command.rb:298:in `run_this'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command.rb:251:in `run'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/var/lib/gems/1.9.1/gems/cri-2.6.1/lib/cri/command.rb:264:in `run'
/var/lib/gems/1.9.1/gems/r10k-2.4.3/bin/r10k:7:in `<top (required)>'
/usr/local/bin/r10k:23:in `load'
/usr/local/bin/r10k:23:in `<main>'
[2016-11-15 08:58:45 - DEBUG1] No unmanaged contents in /etc/puppet/environments/localdev/modules, nothing to purge
```

For this log I used the following- rather simple-  puppetfile:

```
forge 'forge.puppetlabs.com'
mod 'puppetlabs/concat'
```

I'm not quite sure what triggers this error. Maybe it's the environment r10k is ran in:

macOS Sierra => Vagrant 1.8.7 => Virtualbox Version 5.1.8 r111374 (Qt5.5.1) => Ubuntu 14.04.5 => Ruby 1.9.3p484 => r10k 2.4.3

(I also tried Ruby 2.0 and Ruby 2.3.0 using RVM with no success)

The openssl-version might be interesting, too: openssl 1.0.1f

(I also tried rvm pkg install openssl without any luck)

A workaround is possible by specifying each forge module's git repository, but this is rather cumbersome.

Any ideas?

**Comment by dploeger** [comment]
I've added a [simple configuration for Vagrant based on dploeger/puppetdev-ubuntu16.04](https://github.com/puppetlabs/r10k/files/633845/r10k-670.zip), which displays the error. You can simply unzip that file and run "vagrant up" in the directory. The issue is displayed in the provisioning phase.

You can use vagrant ssh to access the vm. The following environment variables are used when running "_r10k puppetfile install_" during provisioning:

```
PUPPETFILE=/etc/puppet/environments/localdev/Puppetfile
PUPPETFILE_DIR=/etc/puppet/environments/localdev/modules
```

**Comment by dploeger** [comment]
This maybe caused by the following bug: https://www.virtualbox.org/ticket/16084

However, using VirtualBox 5.1.10 resolves the issue.
