### ISSUE TITLE
r10k blows up if Puppetfile contains non-git modules

### ISSUE THREAD

**Issue by justinstoller** [puppetlabs/r10k#7]

**Comment by adrienthebo** [comment]
Pardon the slow response; I just discovered that I wasn't watching a bunch of my own repositories. I'll be reviewing this shortly. Thanks!

**Comment by adrienthebo** [comment]
@justinstoller could you provide the output of the command that fails with the `--trace` flag and attach the output here?

**Comment by hunner** [comment]
```
vv% bundle exec r10k -c r10k.yaml environment deploy master --trace

Runtime error: #<RuntimeError: Module fiddyspence/sysctl with args [] doesn't have an implementation. (Are you using the right arguments?)>
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/module.rb:29:in `new'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/root.rb:52:in `modules'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/root.rb:49:in `map'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/root.rb:49:in `modules'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/root.rb:39:in `sync_modules!'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/root.rb:35:in `sync!'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/action/environment.rb:32:in `call'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/lib/r10k/cli/environment/deploy.rb:42:in `command'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/cri-2.3.0/lib/cri/command.rb:296:in `call'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/cri-2.3.0/lib/cri/command.rb:296:in `run_this'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/cri-2.3.0/lib/cri/command.rb:249:in `run'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/cri-2.3.0/lib/cri/command.rb:262:in `run'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/gems/r10k-0.0.9/bin/r10k:7
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/bin/r10k:19:in `load'
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/bin/r10k:19
/Users/hunner/.rvm/gems/ree-1.8.7-2010.02/bin/ruby_noexec_wrapper:14
```

The module file contains

``` ruby
forge "http://forge.puppetlabs.com"

mod 'fiddyspence/sysctl'
# [...]
```

**Comment by adrienthebo** [comment]
The Puppetfile syntax is really loose, so I have to detect what sort of back end to use. For instance, the Forge detection (https://github.com/adrienthebo/r10k/blob/master/lib/r10k/module/forge.rb#L13) will respond to `mod 'module/name', 'version'`, and the version argument is mandatory. Would it be better to check the name for 'one/two' and if no version is given, then try to get it from the Forge?

**Comment by adrienthebo** [comment]
This seems to be the same issue as GH-21; I'm going to close this and move the discussion to that ticket.
