### ISSUE TITLE
r10k 2.6.3 does not install on Windows, due to usage of symbolic link

### ISSUE THREAD

**Issue by Raskil** [puppetlabs/r10k#833]
Hi,

I'm not able to install the r10k gem under Windows anymore. When I do a gem install r10k I get the following error:
```
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:388:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:388:in `block (2 levels) in extract_tar_gz'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package/tar_reader.rb:65:in `each'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:365:in `block in extract_tar_gz'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:482:in `block in open_tar_gz'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:479:in `wrap'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:479:in `open_tar_gz'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:364:in `extract_tar_gz'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:345:in `block (2 levels) in extract_files'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package/tar_reader.rb:65:in `each'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:342:in `block in extract_files'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package/file_source.rb:30:in `open'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package/file_source.rb:30:in `with_read_io'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/package.rb:339:in `extract_files'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:798:in `extract_files'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:307:in `install'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/resolver/specification.rb:97:in `install'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:168:in `block in install'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:156:in `each'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:156:in `install'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:205:in `install_gem'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:255:in `block in install_gems'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:251:in `each'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:251:in `install_gems'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:158:in `execute'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/command.rb:313:in `invoke_with_build_args'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:171:in `process_args'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:141:in `run'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/gem_runner.rb:59:in `run'
        from C:/Ruby21-x64/bin/gem:21:in `<main>'
```

Doing a gem install r10k -v 2.6.2 works fine.

**Comment by sevendials** [comment]
Looks to me like the gem now includes the symbolic link, 'test' (see last line in paste).

I don't see any change to the gemspec. Perhaps there was a change in gem build process?

```foobar:~# ls -l /usr/lib/ruby/gems/2.5.0/gems/r10k-2.6.2/
total 100
-rw-r--r--    1 root     root         60340 Aug 25 07:19 CHANGELOG.mkd
-rw-r--r--    1 root     root          4498 Aug 25 07:19 CONTRIBUTING.mkd
-rw-r--r--    1 root     root           275 Aug 25 07:19 Gemfile
-rw-r--r--    1 root     root           560 Aug 25 07:19 LICENSE
-rw-r--r--    1 root     root           528 Aug 25 07:19 MAINTAINERS
-rw-r--r--    1 root     root          3798 Aug 25 07:19 README.mkd
-rw-r--r--    1 root     root           180 Aug 25 07:19 Rakefile
drwxr-xr-x    2 root     root            60 Aug 25 07:19 bin
drwxr-xr-x    4 root     root           180 Aug 25 07:19 doc
drwxr-xr-x    9 root     root           240 Aug 25 07:19 integration
drwxr-xr-x    3 root     root            80 Aug 25 07:19 lib
drwxr-xr-x    2 root     root            60 Aug 25 07:19 locales
-rw-r--r--    1 root     root          1334 Aug 25 07:19 r10k.gemspec
-rw-r--r--    1 root     root          4846 Aug 25 07:19 r10k.yaml.example
drwxr-xr-x    9 root     root           220 Aug 25 07:19 spec

foobar:~# ls -l /usr/lib/ruby/gems/2.5.0/gems/r10k-2.6.3/
total 100
-rw-r--r--    1 root     root         60399 Aug 25 07:26 CHANGELOG.mkd
-rw-r--r--    1 root     root          4498 Aug 25 07:26 CONTRIBUTING.mkd
-rw-r--r--    1 root     root           275 Aug 25 07:26 Gemfile
-rw-r--r--    1 root     root           560 Aug 25 07:26 LICENSE
-rw-r--r--    1 root     root           528 Aug 25 07:26 MAINTAINERS
-rw-r--r--    1 root     root          3798 Aug 25 07:26 README.mkd
-rw-r--r--    1 root     root           180 Aug 25 07:26 Rakefile
drwxr-xr-x    2 root     root            60 Aug 25 07:26 bin
drwxr-xr-x    4 root     root           180 Aug 25 07:26 doc
drwxr-xr-x    9 root     root           240 Aug 25 07:26 integration
drwxr-xr-x    3 root     root            80 Aug 25 07:26 lib
drwxr-xr-x    2 root     root            60 Aug 25 07:26 locales
-rw-r--r--    1 root     root          1334 Aug 25 07:26 r10k.gemspec
-rw-r--r--    1 root     root          4846 Aug 25 07:26 r10k.yaml.example
drwxr-xr-x    9 root     root           220 Aug 25 07:26 spec
lrwxrwxrwx    1 root     root            13 Aug 25 07:26 test -> ./integration
```

**Comment by jessereynolds** [comment]
This is still an issue with r10k version 3.1.1 - it cannot be installed on windows due to the symbolic link in the gem. 

This is preventing Windows based Puppet developers from being able to test their control repositories with Onceover. See related issue in Onceover: https://github.com/dylanratcliffe/onceover/issues/204

**Comment by jessereynolds** [comment]
Created a Jira ticket: https://tickets.puppetlabs.com/browse/RK-338
